branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  
install:
  - cpanm Dist::Zilla
  - dzil authordeps --missing | cpanm
  - dzil listdeps --missing | cpanm
  - dzil build
  
script: "dzil test"
